# Generated by Django 3.1.7 on 2021-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(blank=True, default='...'),
        ),
    ]
