# Generated by Django 3.1.7 on 2021-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210330_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='Please write something here...'),
        ),
    ]
