# Generated by Django 3.1.7 on 2021-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210403_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='asker',
            field=models.CharField(default='Anonymous users', max_length=100),
        ),
    ]
