# Generated by Django 3.1.7 on 2021-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_asker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='Please write your title here...', max_length=100),
        ),
    ]
